export const COLORS_DATA = [
  {
    name: 'Preto',
    color: '#000000',
    digit: 0,
    multiplier: 1,
    tolerance: null,
    tempCoef: null,
  },
  {
    name: 'Marrom',
    color: '#B45309', 
    digit: 1,
    multiplier: 10,
    tolerance: '±1%',
    tempCoef: '100 PPM/°C',
  },
  {
    name: 'Vermelho',
    color: '#FF0000',
    digit: 2,
    multiplier: 100,
    tolerance: '±2%',
    tempCoef: '50 PPM/°C',
  },
  {
    name: 'Laranja',
    color: '#FFA500',
    digit: 3,
    multiplier: 1000,
    tolerance: null,
    tempCoef: '15 PPM/°C',
  },
  {
    name: 'Amarelo',
    color: '#FFFF00',
    digit: 4,
    multiplier: 10000,
    tolerance: '±5%',
    tempCoef: '25 PPM/°C',
  },
  {
    name: 'Verde',
    color: '#008000',
    digit: 5,
    multiplier: 100000,
    tolerance: '±0.5%',
    tempCoef: '20 PPM/°C',
  },
  {
    name: 'Azul',
    color: '#0000FF',
    digit: 6,
    multiplier: 1000000,
    tolerance: '±0.25%',
    tempCoef: '10 PPM/°C',
  },
  {
    name: 'Violeta',
    color: '#8A2BE2',
    digit: 7,
    multiplier: 10000000,
    tolerance: '±0.1%',
    tempCoef: '5 PPM/°C',
  },
  {
    name: 'Cinza',
    color: '#808080',
    digit: 8,
    multiplier: 100000000,
    tolerance: '±0.05%',
    tempCoef: '1 PPM/°C',
  },
  {
    name: 'Branco',
    color: '#FFFFFF',
    digit: 9,
    multiplier: 1000000000,
    tolerance: null,
    tempCoef: null,
  },
  {
    name: 'Ouro',
    color: '#FFD700',
    digit: null,
    multiplier: 0.1,
    tolerance: '±5%',
    tempCoef: null,
  },
  {
    name: 'Prata',
    color: '#C0C0C0',
    digit: null,
    multiplier: 0.01,
    tolerance: '±10%',
    tempCoef: null,
  },
];